apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-scan
  name: python-scan
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: python-scan
  type: LoadBalancer 
